"""
NGINX reverse-proxy configuration service.

Generates one server block per deployment, keyed by slug.
Each deployed application gets its own server_name based on:

    <slug>.<PUBLIC_HOST>.nip.io

This avoids subpath routing entirely, so frameworks (Vite, Next.js,
React, Vue, etc.) work without any base-path configuration.

Safety:
  - Every config change is validated with `nginx -t` BEFORE reload.
  - If validation fails, the bad config is rolled back automatically.
  - One bad deployment can never take down the reverse proxy.
"""

import os
import logging
from typing import Optional

from app.services.docker_service import DockerService
from app.core.config import settings

logger = logging.getLogger(__name__)


class NginxConfigError(Exception):
    """Raised when nginx configuration validation or reload fails."""
    pass


class NginxService:
    CONFIG_DIR = "/app/nginx/conf.d/apps"

    @staticmethod
    def _get_server_name(slug: str) -> str:
        """Build the server_name value for a deployment."""
        return f"{slug}.{settings.PUBLIC_HOST}.nip.io"

    @staticmethod
    def _get_deployment_url(slug: str) -> str:
        """Build the full public URL for a deployment."""
        server_name = NginxService._get_server_name(slug)
        port = settings.PUBLIC_PORT
        if port != 80:
            return f"http://{server_name}:{port}"
        return f"http://{server_name}"

    @staticmethod
    def _build_server_block(slug: str, container_name: str, port: int) -> str:
        """Generate a complete nginx server block for a deployment."""
        server_name = NginxService._get_server_name(slug)
        return f"""# Auto-generated by Bonk — do not edit manually.
# Deployment: {slug}

upstream bonk_upstream_{slug.replace('-', '_')} {{
    server {container_name}:{port};
}}

server {{
    listen 80;
    server_name {server_name};

    # Proxy all traffic to the deployed application container.
    location / {{
        proxy_pass http://bonk_upstream_{slug.replace('-', '_')};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Websocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Sensible timeouts for long-running requests / SSE
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }}
}}
"""

    @staticmethod
    def _conf_path(slug: str) -> str:
        return os.path.join(NginxService.CONFIG_DIR, f"{slug}.conf")

    @staticmethod
    def _validate_nginx() -> tuple[bool, str]:
        """
        Run `nginx -t` inside the nginx container.
        Returns (success: bool, output: str).
        """
        client = DockerService._get_client()
        try:
            container = client.containers.get("bonk-nginx")
            result = container.exec_run("nginx -t", stderr=True)
            output = result.output.decode("utf-8", errors="replace")
            return result.exit_code == 0, output
        except Exception as e:
            return False, str(e)

    @staticmethod
    def _reload_nginx() -> tuple[bool, str]:
        """
        Send reload signal to the nginx container.
        Returns (success: bool, output: str).
        """
        client = DockerService._get_client()
        try:
            container = client.containers.get("bonk-nginx")
            result = container.exec_run("nginx -s reload", stderr=True)
            output = result.output.decode("utf-8", errors="replace")
            return result.exit_code == 0, output
        except Exception as e:
            return False, str(e)

    @staticmethod
    def add_or_update_deployment(slug: str, container_name: str, port: int) -> None:
        """
        Write nginx config for a deployment and safely reload.

        If nginx validation fails after writing the config, the config
        file is removed and an NginxConfigError is raised — the previous
        working state is preserved.
        """
        os.makedirs(NginxService.CONFIG_DIR, exist_ok=True)
        conf_path = NginxService._conf_path(slug)

        # Preserve existing config for rollback
        old_config: Optional[str] = None
        if os.path.exists(conf_path):
            with open(conf_path, "r") as f:
                old_config = f.read()

        # Write the new config
        new_config = NginxService._build_server_block(slug, container_name, port)
        with open(conf_path, "w") as f:
            f.write(new_config)
        logger.info(f"Wrote nginx config for {slug} at {conf_path}")

        # Validate
        valid, output = NginxService._validate_nginx()
        if not valid:
            logger.error(f"nginx validation failed for {slug}: {output}")
            # Rollback: restore previous config or remove the bad one
            if old_config is not None:
                with open(conf_path, "w") as f:
                    f.write(old_config)
                logger.info(f"Rolled back nginx config for {slug}")
            else:
                os.remove(conf_path)
                logger.info(f"Removed invalid nginx config for {slug}")
            raise NginxConfigError(
                f"nginx config validation failed for deployment '{slug}': {output}"
            )

        # Reload
        reloaded, reload_output = NginxService._reload_nginx()
        if not reloaded:
            logger.error(f"nginx reload failed for {slug}: {reload_output}")
            # Rollback on reload failure too
            if old_config is not None:
                with open(conf_path, "w") as f:
                    f.write(old_config)
            else:
                os.remove(conf_path)
            # Try to reload with the restored config
            NginxService._reload_nginx()
            raise NginxConfigError(
                f"nginx reload failed for deployment '{slug}': {reload_output}"
            )

        logger.info(f"nginx reloaded successfully with config for {slug}")

    @staticmethod
    def remove_deployment(slug: str) -> None:
        """
        Remove nginx config for a deployment and reload.
        Safe to call even if no config exists.
        """
        conf_path = NginxService._conf_path(slug)
        if not os.path.exists(conf_path):
            logger.debug(f"No nginx config to remove for {slug}")
            return

        # Read for potential rollback
        with open(conf_path, "r") as f:
            backup = f.read()

        os.remove(conf_path)
        logger.info(f"Removed nginx config for {slug}")

        valid, output = NginxService._validate_nginx()
        if not valid:
            # Restore the config — removing it made things worse somehow
            logger.error(f"nginx validation failed after removing {slug}: {output}")
            with open(conf_path, "w") as f:
                f.write(backup)
            logger.warning(f"Restored nginx config for {slug} after validation failure")
            return

        reloaded, reload_output = NginxService._reload_nginx()
        if not reloaded:
            logger.error(f"nginx reload failed after removing {slug}: {reload_output}")
        else:
            logger.info(f"nginx reloaded after removing config for {slug}")

    @staticmethod
    def reload() -> None:
        """
        Validate and reload nginx. Used by callers that need a manual reload.
        """
        valid, output = NginxService._validate_nginx()
        if not valid:
            logger.error(f"nginx validation failed during manual reload: {output}")
            raise NginxConfigError(f"nginx validation failed: {output}")

        reloaded, reload_output = NginxService._reload_nginx()
        if not reloaded:
            logger.error(f"nginx reload failed: {reload_output}")
            raise NginxConfigError(f"nginx reload failed: {reload_output}")

        logger.info("nginx reloaded successfully (manual)")

    @staticmethod
    def cleanup_stale_configs(active_slugs: set[str]) -> None:
        """
        Remove any .conf files in the apps directory that don't correspond
        to an active deployment slug. Prevents stale configs from accumulating.
        """
        if not os.path.exists(NginxService.CONFIG_DIR):
            return

        removed = []
        for filename in os.listdir(NginxService.CONFIG_DIR):
            if not filename.endswith(".conf"):
                continue
            slug = filename[:-5]  # strip .conf
            if slug not in active_slugs:
                filepath = os.path.join(NginxService.CONFIG_DIR, filename)
                os.remove(filepath)
                removed.append(slug)
                logger.info(f"Removed stale nginx config for {slug}")

        if removed:
            try:
                NginxService.reload()
            except NginxConfigError:
                logger.warning("Failed to reload nginx after stale config cleanup")
