"""Add deployment URL and port

Revision ID: 24d2467bceb0
Revises: c4f0a0f8e91a
Create Date: 2026-07-26 21:50:52.957239
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d2467bceb0'
down_revision: Union[str, None] = 'c4f0a0f8e91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('host_port', sa.Integer(), nullable=True))
    op.add_column('deployments', sa.Column('deployment_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'deployment_url')
    op.drop_column('deployments', 'host_port')
    # ### end Alembic commands ###
