"""Add deployments table

Revision ID: ab386d8e4d70
Revises: da5922d2fbbc
Create Date: 2026-07-23 02:01:00.632130
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab386d8e4d70'
down_revision: Union[str, None] = 'da5922d2fbbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('deployment_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLONING', 'BUILDING', 'STARTING', 'RUNNING', 'FAILED', 'CANCELED', name='deploymentstatus'), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('commit_message', sa.String(length=255), nullable=True),
    sa.Column('logs_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('active_deployment_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_active_deployment', 'projects', 'deployments', ['active_deployment_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_active_deployment', 'projects', type_='foreignkey')
    op.drop_column('projects', 'active_deployment_id')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
